// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-8N1ib-2_qY4jiVx658XZ98NoySFuGA',
    appId: '1:891571700455:web:14b673096084837089d842',
    messagingSenderId: '891571700455',
    projectId: 'kpknl-kalimantan',
    authDomain: 'kpknl-kalimantan.firebaseapp.com',
    storageBucket: 'kpknl-kalimantan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeFqw47s8aEKpjtJUFvpVrCZQkNwl9fus',
    appId: '1:891571700455:android:4389a1ca332ff7bc89d842',
    messagingSenderId: '891571700455',
    projectId: 'kpknl-kalimantan',
    storageBucket: 'kpknl-kalimantan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rfUuy-k8Gok9tbgmyYiQ7A1yN_1Ssfg',
    appId: '1:891571700455:ios:55910b0e70c160db89d842',
    messagingSenderId: '891571700455',
    projectId: 'kpknl-kalimantan',
    storageBucket: 'kpknl-kalimantan.appspot.com',
    iosClientId: '891571700455-v404gc1vrdagv4ui2rqsl00u2hd3i3jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpknl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-rfUuy-k8Gok9tbgmyYiQ7A1yN_1Ssfg',
    appId: '1:891571700455:ios:55910b0e70c160db89d842',
    messagingSenderId: '891571700455',
    projectId: 'kpknl-kalimantan',
    storageBucket: 'kpknl-kalimantan.appspot.com',
    iosClientId: '891571700455-v404gc1vrdagv4ui2rqsl00u2hd3i3jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpknl',
  );
}
